### ISSUE TITLE
Release update

### ISSUE THREAD

**Issue by rbu** [kyl191/nginx-stable-pagespeed#1]
Hey @kyl191 thanks for providing this package on COPR. Are you still maintaining it?

If so, would it be possible to make another release. There's been bugfixes to ngx_pagespeed at https://github.com/pagespeed/ngx_pagespeed/releases as well as security issues in nginx 1.10.3, see http://mailman.nginx.org/pipermail/nginx-announce/2017/000200.html

**Comment by kyl191** [comment]
Yeah, I saw the announcement email a while back. I'm been doing some travel, haven't had the time to update all 3 versions.

Are you on centos 7?

**Comment by rbu** [comment]
I have this deployed on CentOS 6 and 7, actually.

**Comment by kyl191** [comment]
New spec file in https://github.com/kyl191/nginx-stable-pagespeed/commit/967a50d0c31b9c8c51dfc00d68fee12a67a3cc51

Built on copr, failed on Fedora 26, but the new version should have been released for CentOS 6 & 7.

**Comment by kyl191** [comment]
specific bug is https://trac.nginx.org/nginx/ticket/1259, patch is provided. If the build isn't in the centos repos I'll work on adding the patch, otherwise wait for it to hit the stable version.

**Comment by rbu** [comment]
Hey thanks for the quick update. I've run tests against this version and it looks fine except for the a pagespeed bug we're still seeing. Any chance you could push to 1.12.34.2 stable? It's still using the beta release from half a year ago.

**Comment by kyl191** [comment]
The weird thing is stable and beta are the same code: https://github.com/pagespeed/ngx_pagespeed/compare/v1.12.34.2-stable...v1.12.34.2-beta

**Comment by rbu** [comment]
You're absolutely right. I assumed the recent stable tag was for a recent master. Thanks for pushing the update then, I'll have to sit this one out upstream.

**Comment by kyl191** [comment]
No problem. I was working on a tool that would automate releases, will likely be picking it up again in the near future, so the long wait will hopefully not happen again.
